name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-server:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET:                 ${{ secrets.JWT_SECRET }}
      ATLAS_URI:                  ${{ secrets.ATLAS_URI }}
      BCRYPT_SALT_ROUNDS:         ${{ secrets.BCRYPT_SALT_ROUNDS }}
      PORT:                       ${{ vars.PORT }}
      ALLOWED_ORIGIN:             ${{ vars.ALLOWED_ORIGIN }}
      ACCESS_TOKEN_EXPIRY:        ${{ vars.ACCESS_TOKEN_EXPIRY }}
      REFRESH_TOKEN_EXPIRY:       ${{ vars.REFRESH_TOKEN_EXPIRY }}
      REFRESH_TOKEN_EXPIRY_GUEST: ${{ vars.REFRESH_TOKEN_EXPIRY_GUEST }}
      BOARD_NAME_MAX_LENGTH:      ${{ vars.BOARD_NAME_MAX_LENGTH }}
      DISPLAY_NAME_MAX_LENGTH:    ${{ vars.DISPLAY_NAME_MAX_LENGTH }}
      BOARD_MAX_OBJECTS:          ${{ vars.BOARD_MAX_OBJECTS }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Type-check code
        run: npx tsc --noEmit
        working-directory: ./server

      - name: Run tests
        run: npm test
        working-directory: ./server
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Type-check code
        run: npx tsc --noEmit
        working-directory: ./client

      - name: Run tests
        run: npm test
        working-directory: ./client