name: CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20

      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
        with:
          path: server/node_modules
          key: server-${{ hashFiles('server/package-lock.json') }}
          restore-keys: server-

      - name: Install dependencies
        run: npm install
        working-directory: ./server
      - name: Type-check code
        run: npx tsc --noEmit
        working-directory: ./server
      - name: Run tests
        run: npm test
        working-directory: ./server
  build-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 20


      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 #v4.3.0
        with:
          path: client/node_modules
          key: client-${{ hashFiles('client/package-lock.json') }}
          restore-keys: client-
      - name: Install dependencies
        run: npm install
        working-directory: ./client
      - name: Type-check code
        run: npx tsc --noEmit
        working-directory: ./client
      - name: Run tests
        run: npm test
        working-directory: ./client


  deploy-server:
    runs-on: ubuntu-latest
    needs: [build-client, build-server]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy server to VPS
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 #v1.2.5
        with:
          host:     ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          script:   /opt/chalk/deploy-server.sh

  deploy-client:
    runs-on: ubuntu-latest
    needs: [build-client, build-server]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy client to VPS
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 #v1.2.5
        with:
          host:     ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          script:   /opt/chalk/deploy-client.sh